### ISSUE TITLE
Why not auto-append the monolog channel as hashtag?

### ISSUE THREAD

**Issue by pnoeric** [stackify/stackify-log-monolog#11]
Like the title says ;-) channels already exist in monolog to break log messages into various segments - billing, security, main, etc.

I wrote a custom processor to add '#' plus the channel name to my mesages that get sent to Stackify, so I can search the logs easily using y'alls nice hashtag feature. But it really should just be a part of this handler, no?

This is my very simple processor BTW
```

// set up Monolog
use Monolog\Logger;
use Stackify\Log\Monolog\Handler as StackifyHandler;
use Stackify\Log\Transport\ExecTransport;

$stackify_transport = new ExecTransport( '--my api key--' );
$handler_stackify   = new StackifyHandler( 'Main site', 'Production', $stackify_transport );

// Now create the main logger and tell it where to send the messages
$log = new Logger( 'billing' );

// add hashtag for stackify
$log->pushProcessor( function ( $record ) {
	// https://github.com/Seldaek/monolog/blob/master/doc/message-structure.md
	$record['message'] .= ' #billing';

	return $record;
} );

$log->pushHandler( $handler_stackify );

```

**Comment by paul-hendrick** [comment]
Using a custom processor to modify `$record['message']` gets the job done, but it defies Monolog's convention somewhat, and would be less feasible in Monolog v3, where the property is read-only:
 
- https://github.com/Seldaek/monolog/issues/1814#issuecomment-1596855516
- https://github.com/Seldaek/monolog/commit/38fd8efb89a7b0a893675b666ed40f154266f47a

What would be ideal is if the handler could take in the `channel` and `extra` fields of [Monolog\LogRecord](https://github.com/Seldaek/monolog/blob/main/src/Monolog/LogRecord.php), although I'm not sure if the model on Stackify's side has anywhere for this to go

**Comment by homiedopie** [comment]
Hi @pnoeric @paul-hendrick - This feature is now released. You may need to add new arguments to include channel and extra in context for this to work.

stackify/stackify-log-monolog?tab=readme-ov-file#handler-level-option
